/**
 * Утилиты для работы с Claude Code settings.json (runtime hooks).
 * Чтение/запись конфига, генерация агрегирующих скриптов для hooks.
 */

import fs from 'fs';
import path from 'path';
import os from 'os';

/** Путь к settings.json Claude Code */
export function getClaudeSettingsPath(scope: 'global' | 'project', projectDir?: string, homeDir?: string): string {
  const home = homeDir ?? os.homedir();
  const base = scope === 'global'
    ? path.join(home, '.claude')
    : path.join(projectDir ?? process.cwd(), '.claude');
  return path.join(base, 'settings.json');
}

/** Читает settings.json, возвращает объект (или {} если файла нет) */
export function readClaudeSettings(scope: 'global' | 'project', projectDir?: string, homeDir?: string): Record<string, unknown> {
  const filePath = getClaudeSettingsPath(scope, projectDir, homeDir);
  if (!fs.existsSync(filePath)) return {};
  try {
    const raw = fs.readFileSync(filePath, 'utf-8');
    return JSON.parse(raw) as Record<string, unknown>;
  } catch {
    return {};
  }
}

/** Записывает settings.json (создаёт директории при необходимости) */
export function writeClaudeSettings(scope: 'global' | 'project', data: Record<string, unknown>, projectDir?: string, homeDir?: string): void {
  const filePath = getClaudeSettingsPath(scope, projectDir, homeDir);
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n');
}

/** Генерирует Node.js агрегирующий скрипт для hook-а */
export function generateHookAggregator(hookName: string, skillsDir: string): string {
  return `// Auto-generated by skill-hub. Do not edit manually.
const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

const skillsDir = ${JSON.stringify(skillsDir)};
const hookName = ${JSON.stringify(hookName)};

function runHooks(dir) {
  if (!fs.existsSync(dir)) return;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const hookDir = path.join(dir, entry.name, 'hooks');
    if (!fs.existsSync(hookDir)) continue;
    for (const file of fs.readdirSync(hookDir)) {
      const base = path.basename(file, path.extname(file));
      if (base !== hookName) continue;
      const fullPath = path.join(hookDir, file);
      const ext = path.extname(file).toLowerCase();
      if (ext === '.js') {
        spawnSync(process.execPath, [fullPath], { stdio: 'inherit' });
      } else if (ext === '.sh') {
        spawnSync('sh', [fullPath], { stdio: 'inherit' });
      } else {
        spawnSync(fullPath, [], { stdio: 'inherit', shell: true });
      }
    }
  }
}

runHooks(skillsDir);
`;
}

/** Возвращает путь к директории скиллов Claude Code */
export function getClaudeSkillsDir(scope: 'global' | 'project', projectDir?: string, homeDir?: string): string {
  const home = homeDir ?? os.homedir();
  const base = scope === 'global'
    ? path.join(home, '.claude')
    : path.join(projectDir ?? process.cwd(), '.claude');
  return path.join(base, 'skills');
}
